/********************************************************************************
** Form generated from reading UI file 'othello.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_OTHELLO_H
#define UI_OTHELLO_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Othello
{
public:
    QPushButton *c000;
    QPushButton *c011;
    QPushButton *c033;
    QPushButton *c055;
    QPushButton *c022;
    QPushButton *c066;
    QPushButton *c044;
    QPushButton *c077;
    QPushButton *c100;
    QPushButton *c177;
    QPushButton *c111;
    QPushButton *c122;
    QPushButton *c133;
    QPushButton *c166;
    QPushButton *c144;
    QPushButton *c155;
    QPushButton *c200;
    QPushButton *c277;
    QPushButton *c211;
    QPushButton *c222;
    QPushButton *c233;
    QPushButton *c266;
    QPushButton *c244;
    QPushButton *c255;
    QPushButton *c300;
    QPushButton *c377;
    QPushButton *c311;
    QPushButton *c322;
    QPushButton *c333;
    QPushButton *c366;
    QPushButton *c344;
    QPushButton *c355;
    QPushButton *c400;
    QPushButton *c477;
    QPushButton *c411;
    QPushButton *c422;
    QPushButton *c433;
    QPushButton *c466;
    QPushButton *c444;
    QPushButton *c455;
    QPushButton *c500;
    QPushButton *c577;
    QPushButton *c511;
    QPushButton *c522;
    QPushButton *c533;
    QPushButton *c566;
    QPushButton *c544;
    QPushButton *c555;
    QPushButton *c600;
    QPushButton *c677;
    QPushButton *c611;
    QPushButton *c622;
    QPushButton *c633;
    QPushButton *c666;
    QPushButton *c644;
    QPushButton *c655;
    QPushButton *c700;
    QPushButton *c777;
    QPushButton *c711;
    QPushButton *c722;
    QPushButton *c733;
    QPushButton *c766;
    QPushButton *c744;
    QPushButton *c755;
    QLabel *jugador;
    QLabel *labelNegras;
    QLabel *labelBlancas;
    QPushButton *BotonNuevo;
    QPushButton *BotonSalir;
    QPushButton *BotonSuge;
    QLabel *label;
    QPushButton *Salir;
    QPushButton *Creditos;
    QPushButton *Ayuda;
    QPushButton *ganador;
    QPushButton *jugvsjug;
    QPushButton *jugvscom;
    QPushButton *ayudita;
    QPushButton *creditoMenu;
    QPushButton *facil;
    QPushButton *dificil;
    QButtonGroup *buttonGroup;

    void setupUi(QWidget *Othello)
    {
        if (Othello->objectName().isEmpty())
            Othello->setObjectName(QStringLiteral("Othello"));
        Othello->setEnabled(true);
        Othello->resize(600, 600);
        c000 = new QPushButton(Othello);
        buttonGroup = new QButtonGroup(Othello);
        buttonGroup->setObjectName(QStringLiteral("buttonGroup"));
        buttonGroup->setExclusive(true);
        buttonGroup->addButton(c000);
        c000->setObjectName(QStringLiteral("c000"));
        c000->setGeometry(QRect(90, 100, 50, 50));
        c011 = new QPushButton(Othello);
        buttonGroup->addButton(c011);
        c011->setObjectName(QStringLiteral("c011"));
        c011->setGeometry(QRect(140, 100, 50, 50));
        c033 = new QPushButton(Othello);
        buttonGroup->addButton(c033);
        c033->setObjectName(QStringLiteral("c033"));
        c033->setGeometry(QRect(240, 100, 50, 50));
        c055 = new QPushButton(Othello);
        buttonGroup->addButton(c055);
        c055->setObjectName(QStringLiteral("c055"));
        c055->setGeometry(QRect(340, 100, 50, 50));
        c022 = new QPushButton(Othello);
        buttonGroup->addButton(c022);
        c022->setObjectName(QStringLiteral("c022"));
        c022->setGeometry(QRect(190, 100, 50, 50));
        c066 = new QPushButton(Othello);
        buttonGroup->addButton(c066);
        c066->setObjectName(QStringLiteral("c066"));
        c066->setGeometry(QRect(390, 100, 50, 50));
        c044 = new QPushButton(Othello);
        buttonGroup->addButton(c044);
        c044->setObjectName(QStringLiteral("c044"));
        c044->setGeometry(QRect(290, 100, 50, 50));
        c077 = new QPushButton(Othello);
        buttonGroup->addButton(c077);
        c077->setObjectName(QStringLiteral("c077"));
        c077->setGeometry(QRect(440, 100, 50, 50));
        c100 = new QPushButton(Othello);
        buttonGroup->addButton(c100);
        c100->setObjectName(QStringLiteral("c100"));
        c100->setGeometry(QRect(90, 150, 50, 50));
        c177 = new QPushButton(Othello);
        buttonGroup->addButton(c177);
        c177->setObjectName(QStringLiteral("c177"));
        c177->setGeometry(QRect(440, 150, 50, 50));
        c111 = new QPushButton(Othello);
        buttonGroup->addButton(c111);
        c111->setObjectName(QStringLiteral("c111"));
        c111->setGeometry(QRect(140, 150, 50, 50));
        c122 = new QPushButton(Othello);
        buttonGroup->addButton(c122);
        c122->setObjectName(QStringLiteral("c122"));
        c122->setGeometry(QRect(190, 150, 50, 50));
        c133 = new QPushButton(Othello);
        buttonGroup->addButton(c133);
        c133->setObjectName(QStringLiteral("c133"));
        c133->setGeometry(QRect(240, 150, 50, 50));
        c166 = new QPushButton(Othello);
        buttonGroup->addButton(c166);
        c166->setObjectName(QStringLiteral("c166"));
        c166->setGeometry(QRect(390, 150, 50, 50));
        c144 = new QPushButton(Othello);
        buttonGroup->addButton(c144);
        c144->setObjectName(QStringLiteral("c144"));
        c144->setGeometry(QRect(290, 150, 50, 50));
        c155 = new QPushButton(Othello);
        buttonGroup->addButton(c155);
        c155->setObjectName(QStringLiteral("c155"));
        c155->setGeometry(QRect(340, 150, 50, 50));
        c200 = new QPushButton(Othello);
        buttonGroup->addButton(c200);
        c200->setObjectName(QStringLiteral("c200"));
        c200->setGeometry(QRect(90, 200, 50, 50));
        c277 = new QPushButton(Othello);
        buttonGroup->addButton(c277);
        c277->setObjectName(QStringLiteral("c277"));
        c277->setGeometry(QRect(440, 200, 50, 50));
        c211 = new QPushButton(Othello);
        buttonGroup->addButton(c211);
        c211->setObjectName(QStringLiteral("c211"));
        c211->setGeometry(QRect(140, 200, 50, 50));
        c222 = new QPushButton(Othello);
        buttonGroup->addButton(c222);
        c222->setObjectName(QStringLiteral("c222"));
        c222->setGeometry(QRect(190, 200, 50, 50));
        c233 = new QPushButton(Othello);
        buttonGroup->addButton(c233);
        c233->setObjectName(QStringLiteral("c233"));
        c233->setGeometry(QRect(240, 200, 50, 50));
        c266 = new QPushButton(Othello);
        buttonGroup->addButton(c266);
        c266->setObjectName(QStringLiteral("c266"));
        c266->setGeometry(QRect(390, 200, 50, 50));
        c244 = new QPushButton(Othello);
        buttonGroup->addButton(c244);
        c244->setObjectName(QStringLiteral("c244"));
        c244->setGeometry(QRect(290, 200, 50, 50));
        c255 = new QPushButton(Othello);
        buttonGroup->addButton(c255);
        c255->setObjectName(QStringLiteral("c255"));
        c255->setGeometry(QRect(340, 200, 50, 50));
        c300 = new QPushButton(Othello);
        buttonGroup->addButton(c300);
        c300->setObjectName(QStringLiteral("c300"));
        c300->setGeometry(QRect(90, 250, 50, 50));
        c377 = new QPushButton(Othello);
        buttonGroup->addButton(c377);
        c377->setObjectName(QStringLiteral("c377"));
        c377->setGeometry(QRect(440, 250, 50, 50));
        c311 = new QPushButton(Othello);
        buttonGroup->addButton(c311);
        c311->setObjectName(QStringLiteral("c311"));
        c311->setGeometry(QRect(140, 250, 50, 50));
        c322 = new QPushButton(Othello);
        buttonGroup->addButton(c322);
        c322->setObjectName(QStringLiteral("c322"));
        c322->setGeometry(QRect(190, 250, 50, 50));
        c333 = new QPushButton(Othello);
        buttonGroup->addButton(c333);
        c333->setObjectName(QStringLiteral("c333"));
        c333->setGeometry(QRect(240, 250, 50, 50));
        c366 = new QPushButton(Othello);
        buttonGroup->addButton(c366);
        c366->setObjectName(QStringLiteral("c366"));
        c366->setGeometry(QRect(390, 250, 50, 50));
        c344 = new QPushButton(Othello);
        buttonGroup->addButton(c344);
        c344->setObjectName(QStringLiteral("c344"));
        c344->setGeometry(QRect(290, 250, 50, 50));
        c355 = new QPushButton(Othello);
        buttonGroup->addButton(c355);
        c355->setObjectName(QStringLiteral("c355"));
        c355->setGeometry(QRect(340, 250, 50, 50));
        c400 = new QPushButton(Othello);
        buttonGroup->addButton(c400);
        c400->setObjectName(QStringLiteral("c400"));
        c400->setGeometry(QRect(90, 300, 50, 50));
        c477 = new QPushButton(Othello);
        buttonGroup->addButton(c477);
        c477->setObjectName(QStringLiteral("c477"));
        c477->setGeometry(QRect(440, 300, 50, 50));
        c411 = new QPushButton(Othello);
        buttonGroup->addButton(c411);
        c411->setObjectName(QStringLiteral("c411"));
        c411->setGeometry(QRect(140, 300, 50, 50));
        c422 = new QPushButton(Othello);
        buttonGroup->addButton(c422);
        c422->setObjectName(QStringLiteral("c422"));
        c422->setGeometry(QRect(190, 300, 50, 50));
        c433 = new QPushButton(Othello);
        buttonGroup->addButton(c433);
        c433->setObjectName(QStringLiteral("c433"));
        c433->setGeometry(QRect(240, 300, 50, 50));
        c466 = new QPushButton(Othello);
        buttonGroup->addButton(c466);
        c466->setObjectName(QStringLiteral("c466"));
        c466->setGeometry(QRect(390, 300, 50, 50));
        c444 = new QPushButton(Othello);
        buttonGroup->addButton(c444);
        c444->setObjectName(QStringLiteral("c444"));
        c444->setGeometry(QRect(290, 300, 50, 50));
        c444->setIconSize(QSize(50, 50));
        c455 = new QPushButton(Othello);
        buttonGroup->addButton(c455);
        c455->setObjectName(QStringLiteral("c455"));
        c455->setGeometry(QRect(340, 300, 50, 50));
        c500 = new QPushButton(Othello);
        buttonGroup->addButton(c500);
        c500->setObjectName(QStringLiteral("c500"));
        c500->setGeometry(QRect(90, 350, 50, 50));
        c577 = new QPushButton(Othello);
        buttonGroup->addButton(c577);
        c577->setObjectName(QStringLiteral("c577"));
        c577->setGeometry(QRect(440, 350, 50, 50));
        c511 = new QPushButton(Othello);
        buttonGroup->addButton(c511);
        c511->setObjectName(QStringLiteral("c511"));
        c511->setGeometry(QRect(140, 350, 50, 50));
        c522 = new QPushButton(Othello);
        buttonGroup->addButton(c522);
        c522->setObjectName(QStringLiteral("c522"));
        c522->setGeometry(QRect(190, 350, 50, 50));
        c533 = new QPushButton(Othello);
        buttonGroup->addButton(c533);
        c533->setObjectName(QStringLiteral("c533"));
        c533->setGeometry(QRect(240, 350, 50, 50));
        c566 = new QPushButton(Othello);
        buttonGroup->addButton(c566);
        c566->setObjectName(QStringLiteral("c566"));
        c566->setGeometry(QRect(390, 350, 50, 50));
        c544 = new QPushButton(Othello);
        buttonGroup->addButton(c544);
        c544->setObjectName(QStringLiteral("c544"));
        c544->setGeometry(QRect(290, 350, 50, 50));
        c544->setIconSize(QSize(50, 50));
        c555 = new QPushButton(Othello);
        buttonGroup->addButton(c555);
        c555->setObjectName(QStringLiteral("c555"));
        c555->setGeometry(QRect(340, 350, 50, 50));
        c600 = new QPushButton(Othello);
        buttonGroup->addButton(c600);
        c600->setObjectName(QStringLiteral("c600"));
        c600->setGeometry(QRect(90, 400, 50, 50));
        c677 = new QPushButton(Othello);
        buttonGroup->addButton(c677);
        c677->setObjectName(QStringLiteral("c677"));
        c677->setGeometry(QRect(440, 400, 50, 50));
        c611 = new QPushButton(Othello);
        buttonGroup->addButton(c611);
        c611->setObjectName(QStringLiteral("c611"));
        c611->setGeometry(QRect(140, 400, 50, 50));
        c622 = new QPushButton(Othello);
        buttonGroup->addButton(c622);
        c622->setObjectName(QStringLiteral("c622"));
        c622->setGeometry(QRect(190, 400, 50, 50));
        c633 = new QPushButton(Othello);
        buttonGroup->addButton(c633);
        c633->setObjectName(QStringLiteral("c633"));
        c633->setGeometry(QRect(240, 400, 50, 50));
        c666 = new QPushButton(Othello);
        buttonGroup->addButton(c666);
        c666->setObjectName(QStringLiteral("c666"));
        c666->setGeometry(QRect(390, 400, 50, 50));
        c644 = new QPushButton(Othello);
        buttonGroup->addButton(c644);
        c644->setObjectName(QStringLiteral("c644"));
        c644->setGeometry(QRect(290, 400, 50, 50));
        c655 = new QPushButton(Othello);
        buttonGroup->addButton(c655);
        c655->setObjectName(QStringLiteral("c655"));
        c655->setGeometry(QRect(340, 400, 50, 50));
        c700 = new QPushButton(Othello);
        buttonGroup->addButton(c700);
        c700->setObjectName(QStringLiteral("c700"));
        c700->setGeometry(QRect(90, 450, 50, 50));
        c777 = new QPushButton(Othello);
        buttonGroup->addButton(c777);
        c777->setObjectName(QStringLiteral("c777"));
        c777->setGeometry(QRect(440, 450, 50, 50));
        c711 = new QPushButton(Othello);
        buttonGroup->addButton(c711);
        c711->setObjectName(QStringLiteral("c711"));
        c711->setGeometry(QRect(140, 450, 50, 50));
        c722 = new QPushButton(Othello);
        buttonGroup->addButton(c722);
        c722->setObjectName(QStringLiteral("c722"));
        c722->setGeometry(QRect(190, 450, 50, 50));
        c733 = new QPushButton(Othello);
        buttonGroup->addButton(c733);
        c733->setObjectName(QStringLiteral("c733"));
        c733->setGeometry(QRect(240, 450, 50, 50));
        c766 = new QPushButton(Othello);
        buttonGroup->addButton(c766);
        c766->setObjectName(QStringLiteral("c766"));
        c766->setGeometry(QRect(390, 450, 50, 50));
        c744 = new QPushButton(Othello);
        buttonGroup->addButton(c744);
        c744->setObjectName(QStringLiteral("c744"));
        c744->setGeometry(QRect(290, 450, 50, 50));
        c755 = new QPushButton(Othello);
        buttonGroup->addButton(c755);
        c755->setObjectName(QStringLiteral("c755"));
        c755->setGeometry(QRect(340, 450, 50, 50));
        jugador = new QLabel(Othello);
        jugador->setObjectName(QStringLiteral("jugador"));
        jugador->setGeometry(QRect(100, 80, 47, 13));
        labelNegras = new QLabel(Othello);
        labelNegras->setObjectName(QStringLiteral("labelNegras"));
        labelNegras->setGeometry(QRect(190, 80, 60, 13));
        labelBlancas = new QLabel(Othello);
        labelBlancas->setObjectName(QStringLiteral("labelBlancas"));
        labelBlancas->setGeometry(QRect(270, 80, 60, 13));
        BotonNuevo = new QPushButton(Othello);
        BotonNuevo->setObjectName(QStringLiteral("BotonNuevo"));
        BotonNuevo->setGeometry(QRect(10, 10, 185, 68));
        BotonSalir = new QPushButton(Othello);
        BotonSalir->setObjectName(QStringLiteral("BotonSalir"));
        BotonSalir->setGeometry(QRect(390, 10, 185, 68));
        BotonSuge = new QPushButton(Othello);
        BotonSuge->setObjectName(QStringLiteral("BotonSuge"));
        BotonSuge->setGeometry(QRect(200, 10, 185, 68));
        label = new QLabel(Othello);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(0, 0, 600, 600));
        Salir = new QPushButton(Othello);
        Salir->setObjectName(QStringLiteral("Salir"));
        Salir->setGeometry(QRect(210, 460, 185, 68));
        Creditos = new QPushButton(Othello);
        Creditos->setObjectName(QStringLiteral("Creditos"));
        Creditos->setGeometry(QRect(210, 370, 185, 68));
        Ayuda = new QPushButton(Othello);
        Ayuda->setObjectName(QStringLiteral("Ayuda"));
        Ayuda->setGeometry(QRect(210, 280, 185, 68));
        ganador = new QPushButton(Othello);
        ganador->setObjectName(QStringLiteral("ganador"));
        ganador->setGeometry(QRect(220, 310, 161, 61));
        jugvsjug = new QPushButton(Othello);
        jugvsjug->setObjectName(QStringLiteral("jugvsjug"));
        jugvsjug->setGeometry(QRect(100, 190, 185, 68));
        jugvscom = new QPushButton(Othello);
        jugvscom->setObjectName(QStringLiteral("jugvscom"));
        jugvscom->setGeometry(QRect(310, 190, 185, 68));
        ayudita = new QPushButton(Othello);
        ayudita->setObjectName(QStringLiteral("ayudita"));
        ayudita->setGeometry(QRect(0, 0, 561, 523));
        creditoMenu = new QPushButton(Othello);
        creditoMenu->setObjectName(QStringLiteral("creditoMenu"));
        creditoMenu->setGeometry(QRect(0, 10, 561, 523));
        facil = new QPushButton(Othello);
        facil->setObjectName(QStringLiteral("facil"));
        facil->setGeometry(QRect(140, 510, 131, 51));
        dificil = new QPushButton(Othello);
        dificil->setObjectName(QStringLiteral("dificil"));
        dificil->setGeometry(QRect(350, 510, 131, 51));
        dificil->raise();
        facil->raise();
        c000->raise();
        c011->raise();
        c033->raise();
        c055->raise();
        c022->raise();
        c066->raise();
        c044->raise();
        c077->raise();
        c100->raise();
        c177->raise();
        c111->raise();
        c122->raise();
        c133->raise();
        c166->raise();
        c144->raise();
        c155->raise();
        c200->raise();
        c277->raise();
        c211->raise();
        c222->raise();
        c233->raise();
        c266->raise();
        c244->raise();
        c255->raise();
        c300->raise();
        c377->raise();
        c311->raise();
        c322->raise();
        c333->raise();
        c366->raise();
        c344->raise();
        c355->raise();
        c400->raise();
        c477->raise();
        c411->raise();
        c422->raise();
        c433->raise();
        c466->raise();
        c444->raise();
        c455->raise();
        c500->raise();
        c577->raise();
        c511->raise();
        c522->raise();
        c533->raise();
        c566->raise();
        c544->raise();
        c555->raise();
        c600->raise();
        c677->raise();
        c611->raise();
        c622->raise();
        c633->raise();
        c666->raise();
        c644->raise();
        c655->raise();
        c700->raise();
        c777->raise();
        c711->raise();
        c722->raise();
        c733->raise();
        c766->raise();
        c744->raise();
        c755->raise();
        jugador->raise();
        labelNegras->raise();
        labelBlancas->raise();
        BotonNuevo->raise();
        BotonSalir->raise();
        BotonSuge->raise();
        label->raise();
        Salir->raise();
        Creditos->raise();
        Ayuda->raise();
        ganador->raise();
        jugvscom->raise();
        jugvsjug->raise();
        ayudita->raise();
        creditoMenu->raise();

        retranslateUi(Othello);
        QObject::connect(BotonSalir, SIGNAL(clicked()), Othello, SLOT(close()));
        QObject::connect(Salir, SIGNAL(clicked()), label, SLOT(close()));
        QObject::connect(Salir, SIGNAL(clicked()), Othello, SLOT(close()));
        QObject::connect(ganador, SIGNAL(clicked()), label, SLOT(show()));
        QObject::connect(ganador, SIGNAL(clicked()), Ayuda, SLOT(show()));
        QObject::connect(ganador, SIGNAL(clicked()), Creditos, SLOT(show()));
        QObject::connect(ganador, SIGNAL(clicked()), Salir, SLOT(show()));
        QObject::connect(ganador, SIGNAL(clicked()), ganador, SLOT(close()));
        QObject::connect(jugvsjug, SIGNAL(clicked()), jugvsjug, SLOT(close()));
        QObject::connect(jugvsjug, SIGNAL(clicked()), jugvscom, SLOT(close()));
        QObject::connect(jugvsjug, SIGNAL(clicked()), Ayuda, SLOT(close()));
        QObject::connect(jugvsjug, SIGNAL(clicked()), Creditos, SLOT(close()));
        QObject::connect(jugvsjug, SIGNAL(clicked()), Salir, SLOT(close()));
        QObject::connect(jugvscom, SIGNAL(clicked()), Ayuda, SLOT(close()));
        QObject::connect(jugvscom, SIGNAL(clicked()), jugvsjug, SLOT(close()));
        QObject::connect(jugvscom, SIGNAL(clicked()), Creditos, SLOT(close()));
        QObject::connect(jugvscom, SIGNAL(clicked()), Salir, SLOT(close()));
        QObject::connect(jugvscom, SIGNAL(clicked()), label, SLOT(close()));
        QObject::connect(jugvsjug, SIGNAL(clicked()), label, SLOT(close()));
        QObject::connect(jugvscom, SIGNAL(clicked()), jugvscom, SLOT(close()));
        QObject::connect(ganador, SIGNAL(clicked()), jugvsjug, SLOT(show()));
        QObject::connect(ganador, SIGNAL(clicked()), jugvscom, SLOT(show()));
        QObject::connect(Ayuda, SIGNAL(clicked()), jugvsjug, SLOT(close()));
        QObject::connect(Ayuda, SIGNAL(clicked()), jugvscom, SLOT(close()));
        QObject::connect(Ayuda, SIGNAL(clicked()), Creditos, SLOT(close()));
        QObject::connect(Ayuda, SIGNAL(clicked()), Salir, SLOT(close()));
        QObject::connect(Ayuda, SIGNAL(clicked()), Ayuda, SLOT(close()));
        QObject::connect(ayudita, SIGNAL(clicked()), ayudita, SLOT(show()));
        QObject::connect(ayudita, SIGNAL(clicked()), ayudita, SLOT(close()));
        QObject::connect(ayudita, SIGNAL(clicked()), jugvscom, SLOT(show()));
        QObject::connect(ayudita, SIGNAL(clicked()), jugvsjug, SLOT(show()));
        QObject::connect(ayudita, SIGNAL(clicked()), Ayuda, SLOT(show()));
        QObject::connect(ayudita, SIGNAL(clicked()), Creditos, SLOT(show()));
        QObject::connect(ayudita, SIGNAL(clicked()), Salir, SLOT(show()));
        QObject::connect(creditoMenu, SIGNAL(clicked()), creditoMenu, SLOT(close()));
        QObject::connect(facil, SIGNAL(clicked()), dificil, SLOT(close()));
        QObject::connect(facil, SIGNAL(clicked()), facil, SLOT(close()));
        QObject::connect(dificil, SIGNAL(clicked()), facil, SLOT(close()));
        QObject::connect(dificil, SIGNAL(clicked()), dificil, SLOT(close()));
        QObject::connect(BotonNuevo, SIGNAL(clicked()), facil, SLOT(show()));
        QObject::connect(BotonNuevo, SIGNAL(clicked()), dificil, SLOT(show()));
        QObject::connect(jugvsjug, SIGNAL(clicked()), facil, SLOT(close()));
        QObject::connect(jugvsjug, SIGNAL(clicked()), dificil, SLOT(close()));

        QMetaObject::connectSlotsByName(Othello);
    } // setupUi

    void retranslateUi(QWidget *Othello)
    {
        Othello->setWindowTitle(QApplication::translate("Othello", "Othello", 0));
        c000->setText(QString());
        c011->setText(QString());
        c033->setText(QString());
        c055->setText(QString());
        c022->setText(QString());
        c066->setText(QString());
        c044->setText(QString());
        c077->setText(QString());
        c100->setText(QString());
        c177->setText(QString());
        c111->setText(QString());
        c122->setText(QString());
        c133->setText(QString());
        c166->setText(QString());
        c144->setText(QString());
        c155->setText(QString());
        c200->setText(QString());
        c277->setText(QString());
        c211->setText(QString());
        c222->setText(QString());
        c233->setText(QString());
        c266->setText(QString());
        c244->setText(QString());
        c255->setText(QString());
        c300->setText(QString());
        c377->setText(QString());
        c311->setText(QString());
        c322->setText(QString());
        c333->setText(QString());
        c366->setText(QString());
        c344->setText(QString());
        c355->setText(QString());
        c400->setText(QString());
        c477->setText(QString());
        c411->setText(QString());
        c422->setText(QString());
        c433->setText(QString());
        c466->setText(QString());
        c444->setText(QString());
        c455->setText(QString());
        c500->setText(QString());
        c577->setText(QString());
        c511->setText(QString());
        c522->setText(QString());
        c533->setText(QString());
        c566->setText(QString());
        c544->setText(QString());
        c555->setText(QString());
        c600->setText(QString());
        c677->setText(QString());
        c611->setText(QString());
        c622->setText(QString());
        c633->setText(QString());
        c666->setText(QString());
        c644->setText(QString());
        c655->setText(QString());
        c700->setText(QString());
        c777->setText(QString());
        c711->setText(QString());
        c722->setText(QString());
        c733->setText(QString());
        c766->setText(QString());
        c744->setText(QString());
        c755->setText(QString());
        jugador->setText(QApplication::translate("Othello", "Jugador 1", 0));
        labelNegras->setText(QString());
        labelBlancas->setText(QString());
        BotonNuevo->setText(QString());
        BotonSalir->setText(QString());
        BotonSuge->setText(QString());
        label->setText(QApplication::translate("Othello", "Q", 0));
        Salir->setText(QString());
        Creditos->setText(QString());
        Ayuda->setText(QString());
        ganador->setText(QApplication::translate("Othello", "Ganador", 0));
        jugvsjug->setText(QString());
        jugvscom->setText(QString());
        ayudita->setText(QString());
        creditoMenu->setText(QString());
        facil->setText(QString());
        dificil->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Othello: public Ui_Othello {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_OTHELLO_H
